sudo: false
language: php

matrix:
  fast_finish: true
  include:
  - php: 5.5
  - php: 5.6
  - php: 7
  - php: hhvm
  allow_failures:
  - php: hhvm

before_install: composer self-update

install: composer install --no-interaction

script: phpunit --configuration $DB.phpunit.xml